# load packages
library(data.table)
library(stringr)

# read in data file
passwords <- data.table(orig=readLines(file("input/P1S2_cond5P2.txt")))
tot <- nrow(passwords) 
passwords$len <- nchar(passwords$orig)
passwords$up_A <- str_count(passwords$orig, "A")
passwords$up_B <- str_count(passwords$orig, "B")
passwords$up_C <- str_count(passwords$orig, "C")
passwords$up_D <- str_count(passwords$orig, "D")
passwords$up_E <- str_count(passwords$orig, "E")
passwords$up_F <- str_count(passwords$orig, "F")
passwords$up_G <- str_count(passwords$orig, "G")
passwords$up_H <- str_count(passwords$orig, "H")
passwords$up_I <- str_count(passwords$orig, "I")
passwords$up_J <- str_count(passwords$orig, "J")
passwords$up_K <- str_count(passwords$orig, "K")
passwords$up_L <- str_count(passwords$orig, "L")
passwords$up_M <- str_count(passwords$orig, "M")
passwords$up_N <- str_count(passwords$orig, "N")
passwords$up_O <- str_count(passwords$orig, "O")
passwords$up_P <- str_count(passwords$orig, "P")
passwords$up_Q <- str_count(passwords$orig, "Q")
passwords$up_R <- str_count(passwords$orig, "R")
passwords$up_S <- str_count(passwords$orig, "S")
passwords$up_T <- str_count(passwords$orig, "T")
passwords$up_U <- str_count(passwords$orig, "U")
passwords$up_V <- str_count(passwords$orig, "V")
passwords$up_W <- str_count(passwords$orig, "W")
passwords$up_X <- str_count(passwords$orig, "X")
passwords$up_Y <- str_count(passwords$orig, "Y")
passwords$up_Z <- str_count(passwords$orig, "Z")
passwords$lw_a <- str_count(passwords$orig, "a")
passwords$lw_b <- str_count(passwords$orig, "b")
passwords$lw_c <- str_count(passwords$orig, "c")
passwords$lw_d <- str_count(passwords$orig, "d")
passwords$lw_e <- str_count(passwords$orig, "e")
passwords$lw_f <- str_count(passwords$orig, "f")
passwords$lw_g <- str_count(passwords$orig, "g")
passwords$lw_h <- str_count(passwords$orig, "h")
passwords$lw_i <- str_count(passwords$orig, "i")
passwords$lw_j <- str_count(passwords$orig, "j")
passwords$lw_k <- str_count(passwords$orig, "k")
passwords$lw_l <- str_count(passwords$orig, "l")
passwords$lw_m <- str_count(passwords$orig, "m")
passwords$lw_n <- str_count(passwords$orig, "n")
passwords$lw_o <- str_count(passwords$orig, "o")
passwords$lw_p <- str_count(passwords$orig, "p")
passwords$lw_q <- str_count(passwords$orig, "q")
passwords$lw_r <- str_count(passwords$orig, "r")
passwords$lw_s <- str_count(passwords$orig, "s")
passwords$lw_t <- str_count(passwords$orig, "t")
passwords$lw_u <- str_count(passwords$orig, "u")
passwords$lw_v <- str_count(passwords$orig, "v")
passwords$lw_w <- str_count(passwords$orig, "w")
passwords$lw_x <- str_count(passwords$orig, "x")
passwords$lw_y <- str_count(passwords$orig, "y")
passwords$lw_z <- str_count(passwords$orig, "z")
passwords$nm_1 <- str_count(passwords$orig, "1")
passwords$nm_2 <- str_count(passwords$orig, "2")
passwords$nm_3 <- str_count(passwords$orig, "3")
passwords$nm_4 <- str_count(passwords$orig, "4")
passwords$nm_5 <- str_count(passwords$orig, "5")
passwords$nm_6 <- str_count(passwords$orig, "6")
passwords$nm_7 <- str_count(passwords$orig, "7")
passwords$nm_8 <- str_count(passwords$orig, "8")
passwords$nm_9 <- str_count(passwords$orig, "9")
passwords$nm_0 <- str_count(passwords$orig, "0")
passwords$sp_grave <- str_count(passwords$orig, "`")
passwords$sp_tilde <- str_count(passwords$orig, "~")
passwords$sp_exclamation <- str_count(passwords$orig, "!")
passwords$sp_at <- str_count(passwords$orig, "@")
passwords$sp_hashtag <- str_count(passwords$orig, "#")
passwords$sp_dollar <- str_count(passwords$orig, "\\$")
passwords$sp_percent <- str_count(passwords$orig, "%")
passwords$sp_caret <- str_count(passwords$orig, "\\^")
passwords$sp_ampersand <- str_count(passwords$orig, "&")
passwords$sp_asterisk <- str_count(passwords$orig, "\\*")
passwords$sp_parenthsL <- str_count(passwords$orig, "\\(")
passwords$sp_parenthsR <- str_count(passwords$orig, "\\)")
passwords$sp_hyphen <- str_count(passwords$orig, "\\-")
passwords$sp_underscore <- str_count(passwords$orig, "_")
passwords$sp_equal <- str_count(passwords$orig, "=")
passwords$sp_plus <- str_count(passwords$orig, "\\+")
passwords$sp_brcktL <- str_count(passwords$orig, "\\[")
passwords$sp_brcktR <- str_count(passwords$orig, "]")
passwords$sp_backslash <- str_count(passwords$orig, "\\\\")
passwords$sp_curlyL <- str_count(passwords$orig, "\\{")
passwords$sp_curlyR <- str_count(passwords$orig, "\\}")
passwords$sp_vbar <- str_count(passwords$orig, "\\|")
passwords$sp_semicolon <- str_count(passwords$orig, ";")
passwords$sp_sgquote <- str_count(passwords$orig, "'")
passwords$sp_colon <- str_count(passwords$orig, ":")
passwords$sp_dblquote <- str_count(passwords$orig, "\"")
passwords$sp_comma <- str_count(passwords$orig, ",")
passwords$sp_period <- str_count(passwords$orig, "\\.")
passwords$sp_slash <- str_count(passwords$orig, "/")
passwords$sp_less <- str_count(passwords$orig, "<")
passwords$sp_greater <- str_count(passwords$orig, ">")
passwords$sp_question <- str_count(passwords$orig, "\\?")
passwords$white_space <- str_count(passwords$orig, " ")

write.table(passwords, "output/P1S2_cond5OUTPUTP2.txt", sep="\t", quote=FALSE, row.names=FALSE)
